apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-app
  labels:
    app: blue-green-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-green-app
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
      - name: app-container
        image: gaurav20161/welcome:v1  # default, overridden by overlays
        ports:
        - containerPort: 80
