apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  selector:
    app: blue-green-app
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
